[book]
title = "NanoC Design Document"
authors = ["NanoC Contributors"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/vincent-lafouasse/NanoC"
additional-js = ["theme/nanoc-highlight.js"]
additional-css = ["theme/nanoc-syntax.css"]
